# Site settings
baseurl = "https://heshed.github.io/"
languageCode = "en-us"
title = "Heshed - Salva"
theme = "Hugo-Octopress"
builddrafts = false

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

canonifyurls = true
SectionPagesMenu = "main"

highlightTheme = "solarized_dark"
paginate = 6

[[menu.sidebar]]
    Name = "GitHub"
    URL = "https://github.com/heshed"
    weight = 0

[[menu.sidebar]]
    Name = "old blog"
    URL = "http://tech-heshed.tumblr.com/"
    weight = 1

[taxonomies]
    author = "authors"
    category = "categories"
    tag = "tags"
    series = "series"

[params]
    truncate = true
    subtitle = "Heshed Heshed"
    # customCSS = ["css/custom.css", "css/custom-font.css"]

    googleAnalytics = "UA-84863059-1"

    disqusShortname = "timo-boll-github"
    rss = true
    textrss = true

    sidebarHeader = ""
    sidebarText = "programming, Golang"
    sidebarRecentLimit = "5"
    sidebarMenuEnabled = true
    sidebarMenuHeader = ""
    sidebarNewWindow  = true

    highlightTheme = "solarized_dark"
    searchEngineURL = "https://www.google.com/search"
    continueReadingText = "more.."

    bitbucket = ""
    twitter = ""
    keybase = ""
    stackoverflow = ""
    linkedin = ""
    googleplus = ""
    youtube = ""
    github = "https://github.com/heshed"
    facebook = ""

    tableOfContents = true
    generateTaxonomyList = true
